name: todo_list
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  test: ^1.9.4
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.6
  provider: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Cera
      fonts:
        - asset: assets/fonts/CeraPro.ttf
  assets:
    - assets/images/
